name: Build Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.8'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build web --release
      - name: Pushes to github pages repo
        uses: cpina/github-action-push-to-another-repository@main
        env: 
          API_TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
        with:
          source-directory: 'build/web'
          destination-github-username: 'echocues'
          destination-repository-name: 'echocues.github.io'
          user-email: w1nter.ish3re@gmail.com
          target-branch: main
          
